# Generated by Django 4.2.27 on 2026-01-09 06:47

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(db_index=True, default=app.models.generate_session_code, max_length=20, unique=True)),
                ('host_lat', models.FloatField(blank=True, null=True)),
                ('host_lng', models.FloatField(blank=True, null=True)),
                ('host_last_update', models.DateTimeField(blank=True, null=True)),
                ('visitor_lat', models.FloatField(blank=True, null=True)),
                ('visitor_lng', models.FloatField(blank=True, null=True)),
                ('visitor_last_update', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
